version: '3.4'

services:
  catalogdb: 
    container_name: catalogdb
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=Catalogdb
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=catalogdb;Port=5432;Database=Catalogdb;User Id=admin;Password=admin1234"
    depends_on:
      - catalogdb
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
