version: '3.4'

services:
  catalogdb: 
    container_name: catalogdb
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=Catalogdb
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb: 
    container_name: basketdb
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=Basketdb
    restart: always
    ports: 
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  distributedcache:
    container_name: distributedcache
    restart: always    
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=catalogdb;Port=5432;Database=Catalogdb;User Id=admin;Password=admin1234"
    depends_on:
      - catalogdb
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=basketdb;Port=5432;Database=Basketdb;User Id=admin;Password=admin1234"
      - "DatabaseSettings:Redis=distributedcache:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc:8080"
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Data source=DiscountDb"
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
